FootBallLegueProject.Web/Models/ErrorViewModel.cs
using System;

namespace FootBallLegueProject.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FootBallLegueProject.Web/Models/ViewModels/MatchViewModels/CreateMatchViewModel.cs
using FootballLeague.Services.DTOs;
using Microsoft.AspNetCore.Mvc.Rendering;
using PariplayFootballLeague.Web.Models.ViewModels;
using System;

namespace FootBallLegueProject.Web.Models.ViewModels.MatchViewModels
{
    public class CreateMatchViewModel
    {
        public TeamViewModel TeamOne { get; set; }
        public DateTime EventTime { get; set; }

        public TeamViewModel TeamTwo { get; set; }

      
    }
}

FootBallLegueProject.Web/Models/ViewModels/RankViewModels/RankViewModel.cs
using PariplayFootballLeague.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootBallLegueProject.Web.Models.ViewModels.RankViewModels
{
    public class RankViewModel
    {
        public int TotalPoints { get; set; }
        public TeamViewModel Team  { get; set; }
    }
}

FootBallLegueProject.Web/Models/ViewModels/TeamViewModels/TeamViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace PariplayFootballLeague.Web.Models.ViewModels
{
    [BindProperties]
    public class TeamViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public int TotalScore { get; set; }
    }
}

FootBallLegueProject.Web/Controllers/HomeController.cs
using AutoMapper;
using FootballLeague.Services.Contracts;
using FootBallLegueProject.Web.Models;
using FootBallLegueProject.Web.Models.ViewModels.RankViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace FootBallLegueProject.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRankService rankService;
        private readonly IMapper mapper;
        public HomeController(ILogger<HomeController> logger, IRankService rankService, IMapper mapper)
        {
            this.mapper = mapper; 
            this.rankService = rankService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var r = mapper.Map<IEnumerable<RankViewModel>>
                (this.rankService.GetAll(this.mapper)).AsEnumerable();
            return View("List", mapper.Map<IEnumerable<RankViewModel>>
                (this.rankService.GetAll(this.mapper)).AsEnumerable());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FootBallLegueProject.Web/Controllers/MatchController.cs
using AutoMapper;
using FootballLeague.Services.Contracts;
using FootballLeague.Services.DTOs;
using FootBallLegueProject.Web.Hubs;
using FootBallLegueProject.Web.Models.ViewModels.MatchViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using PariplayFootballLeague.Web.Models.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootBallLegueProject.Web.Controllers
{
    public class MatchController : Controller
    {
        private readonly IMapper mapper;
        private readonly IMatchService matchService;
        private readonly ITeamService teamService;
        private readonly UpdateRankListHub hubContext;
        private readonly IHubContext<UpdateRankListHub> hubContext1;

        public MatchController(IMapper mapper, 
            IMatchService matchService,
            ITeamService teamService, 
            UpdateRankListHub hubContext, 
            IHubContext<UpdateRankListHub> hubcontext1)
        {
            this.hubContext1
                 = hubcontext1;
            this.mapper = mapper;
            this.teamService = teamService;
            this.matchService = matchService;
            this.hubContext = hubContext;

        }
        public IActionResult Index()        
        
        {
            var teamViewModels = mapper.Map<ICollection<TeamViewModel>>(teamService.GetAll(mapper)).ToList();
            ViewData["Create"] = new SelectList(teamViewModels, "Id", "Name", "TotalScore");            
            return View("Create");
        }

        public async Task<IActionResult> Create(CreateMatchViewModel team)
        {
            if(await matchService.Create(mapper.Map<CreateMatchDto>(team), mapper))
            {
                var d = this.hubContext1.Clients;
                await hubContext.Update(d, true);                
            }         
            return RedirectToAction("Index");
        }

    }
}

FootBallLegueProject.Web/Controllers/TeamController.cs
using AutoMapper;
using FootballLeague.Services.Contracts;
using FootballLeague.Services.DTOs;
using FootBallLegueProject.Web.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using PariplayFootballLeague.Web.Models.ViewModels;
using System.Threading.Tasks;

namespace FootBallLegueProject.Web.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamService teamService;
        private readonly IMapper mapper;
        private readonly IHubContext<UpdateRankListHub> hubContext;
        private readonly UpdateRankListHub context;

        public TeamController(ITeamService teamService, IMapper mapper, IHubContext<UpdateRankListHub> hubContext, UpdateRankListHub context)
        {
            this.hubContext = hubContext;
            this.teamService = teamService;
            this.mapper = mapper;
            this.context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Create(TeamViewModel team)
        {
            if(teamService.Create(mapper.Map<BaseTeamDto>(team), mapper)!=null)
            {
                var p = context.Clients;
                var d = this.hubContext.Clients;
                 await context.Update(d, true);
            }
           
            return RedirectToAction("Index");

        }
    }
}

FootBallLegueProject.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FootBallLegueProject.Web/Views/Home/List.cshtml
@model IEnumerable<FootBallLegueProject.Web.Models.ViewModels.RankViewModels.RankViewModel>
@using System.Xml.Linq
@using Microsoft.AspNetCore.SignalR;

@{
    ViewData["Title"] = "List";

    var x = 1;

}
<div id="update">
    <h6>
        If you read this, Thank you for starting the solution, instead of just scrolling down.
        Main goal was to do something different for myself and I will apreciate if you can tell me every big mistake I have done
        so I can learn how to make it better in the future.
        No more chit - chat, please follow this 2 steps and if you have not migrate the DB =>  Open Package Manager Console and write Update-Database
    </h6>





    <p>
        <a asp-controller="Team" asp-action="Index"> Step ONE Create a few New Teams</a>
    </p>

    <div>
        <a asp-controller="Match" asp-action="Index">Step Two  Create a  Match </a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TotalPoints)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPoints)
                    </td>
                    <td>
                        @Html.Partial("~/Views/Team/Details.cshtml", item.Team)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/udapte.js"></script>

FootBallLegueProject.Web/Views/Match/Create.cshtml
@model FootBallLegueProject.Web.Models.ViewModels.MatchViewModels.CreateMatchViewModel

@{
    ViewData["Title"] = "Create";
    var r = ViewBag.Create;
    var x = this.Model;
    var e = 1;
}


<h4>Here is the magic! Please Open a new tab on the browser home page and watch what will happen when you create a new match :)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

          
            <div class="form-group">
                <label asp-for="TeamOne.Id" class="control-label"> Team one</label>
                <select asp-for="TeamOne.Id" class="form-control" asp-items="@ViewBag.Create"></select>
                <span asp-validation-for="TeamOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeamOne.TotalScore" class="control-label">Team one goals</label>
                <input asp-for="TeamOne.TotalScore" class="form-control" />
                <span asp-validation-for="TeamOne.TotalScore" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="TeamTwo.Id" class="control-label">Team two</label>
            <select asp-for="TeamTwo.Id" class="form-control" asp-items="@ViewBag.Create"></select>
            <span asp-validation-for="TeamTwo" class="text-danger"></span>
        </div>
            <div class="form-group">
                <label asp-for="TeamTwo.TotalScore" class="control-label"> Team two goals</label>
                <input asp-for="TeamTwo.TotalScore" class="form-control" />
                <span asp-validation-for="TeamTwo.TotalScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventTime" class="control-label">Date and Time for the event</label>
                <input asp-for="EventTime" class="form-control" />
                <span asp-validation-for="EventTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Rank List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootBallLegueProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FootBallLegueProject.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FootBallLegueProject.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FootBallLegueProject.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

FootBallLegueProject.Web/Views/Team/Details.cshtml
@model PariplayFootballLeague.Web.Models.ViewModels.TeamViewModel

@{
    ViewData["Title"] = "Details";
}


<div>
    <hr />
    <dl class="row">      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalScore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalScore)
        </dd>
    </dl>
</div>


FootBallLegueProject.Web/Views/Team/Index.cshtml
@model PariplayFootballLeague.Web.Models.ViewModels.TeamViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>TeamViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Rank List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}